package com.veles.purchase.platform.ai

import android.content.Context
import android.graphics.BitmapFactory
import android.util.Log
import com.google.mediapipe.framework.image.BitmapImageBuilder
import com.google.mediapipe.tasks.genai.llminference.GraphOptions
import com.google.mediapipe.tasks.genai.llminference.LlmInference
import com.google.mediapipe.tasks.genai.llminference.LlmInferenceSession
import com.veles.purchase.domain.model.scanner.ReceiptData
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import kotlinx.coroutines.withTimeoutOrNull
import java.io.File
import java.util.concurrent.atomic.AtomicBoolean
import kotlin.coroutines.resume

private const val TAG = "LocalVisionParser"
// XNNPack cache generated by TFLite on first run is typically ~800 MB for a 2 GB model
private const val XNNPACK_CACHE_BYTES = 900L * 1024 * 1024

/**
 * Offline receipt parser using Gemma 3n E2B INT4 vision model via MediaPipe LlmInference.
 *
 * The model accepts images directly — no OCR pre-processing needed.
 * Model: google/gemma-3n tfLite gemma-3n-e2b-it-int4 (~2 GB, downloaded on first use).
 */
class LocalMediaPipeVisionParser(
    private val context: Context,
    private val modelFile: File
) : ReceiptAiParser {

    override val engineType: ReceiptAiParser.EngineType = ReceiptAiParser.EngineType.LOCAL_SLM

    private val xnnpackCacheFile: File
        get() = File(context.cacheDir, "${modelFile.name}.xnnpack_cache")

    override suspend fun isAvailable(): Boolean {
        if (!modelFile.exists()) {
            Log.w(TAG, "Model file not found: ${modelFile.absolutePath}")
            return false
        }
        if (modelFile.length() < GemmaModelConfig.MODEL_SIZE_BYTES / 2) {
            Log.w(TAG, "Model file too small: ${modelFile.length() / 1024 / 1024} MB (expected >${GemmaModelConfig.MODEL_SIZE_BYTES / 2 / 1024 / 1024} MB)")
            return false
        }
        // Vision modality requires OpenCL (GPU). Emulators and some low-end devices lack it.
        if (!isOpenClAvailable()) {
            Log.w(TAG, "Vision inference requires OpenCL (GPU). Not available on this device/emulator.")
            return false
        }
        // XNNPack cache not yet built → need extra free space
        if (!xnnpackCacheFile.exists()) {
            val freeBytes = context.cacheDir.freeSpace
            if (freeBytes < XNNPACK_CACHE_BYTES) {
                Log.w(TAG, "Not enough free space for XNNPack cache: ${freeBytes / 1024 / 1024} MB free, need ~${XNNPACK_CACHE_BYTES / 1024 / 1024} MB")
                return false
            }
        }
        Log.d(TAG, "isAvailable=true, model=${modelFile.name} (${modelFile.length() / 1024 / 1024} MB)")
        return true
    }

    private fun isOpenClAvailable(): Boolean = try {
        System.loadLibrary("OpenCL")
        true
    } catch (e: UnsatisfiedLinkError) {
        false
    }

    override suspend fun parse(imageBytes: ByteArray): ReceiptData? {
        if (!isAvailable()) return null

        return try {
            val prompt = ReceiptPromptBuilder.buildPrompt()

            // Vision encoder is slow on device — resize to 512px to reduce prefill time.
            val response: String? = withTimeoutOrNull(600_000L) {
                withContext(Dispatchers.IO) {
                    val raw = BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.size)
                        ?: return@withContext null
                    val bitmap = resizeForVision(raw)
                    Log.d(TAG, "Image resized to ${bitmap.width}x${bitmap.height} for vision inference")
                    val mpImage = BitmapImageBuilder(bitmap).build()

                    Log.d(TAG, "Creating LlmInference from model: ${modelFile.name}")
                    val llmOpts = LlmInference.LlmInferenceOptions.builder()
                        .setModelPath(modelFile.absolutePath)
                        .setMaxTokens(GemmaModelConfig.MAX_TOKENS)
                        .setMaxNumImages(GemmaModelConfig.MAX_IMAGES)
                        // Do NOT force CPU — let MediaPipe pick GPU (OpenCL) on supported devices.
                        // isAvailable() already guarantees OpenCL is present.
                        .build()

                    val sessionOpts = LlmInferenceSession.LlmInferenceSessionOptions.builder()
                        .setTopK(GemmaModelConfig.TOP_K)
                        .setTemperature(GemmaModelConfig.TEMPERATURE)
                        .setGraphOptions(
                            GraphOptions.builder().setEnableVisionModality(true).build()
                        )
                        .build()

                    Log.d(TAG, "Creating LlmInferenceSession with vision modality")
                    LlmInference.createFromOptions(context, llmOpts).use { llm ->
                        LlmInferenceSession.createFromOptions(llm, sessionOpts).use { session ->
                            suspendCancellableCoroutine { cont ->
                                val sb = StringBuilder()
                                val stopFlag = AtomicBoolean(false)
                                var earlyResult: String? = null

                                session.addQueryChunk(prompt)
                                session.addImage(mpImage)
                                Log.d(TAG, "Starting generateResponseAsync")

                                session.generateResponseAsync { partial, done ->
                                    if (!stopFlag.get()) {
                                        sb.append(partial)
                                        val text = sb.toString()
                                        if (sb.length % 200 == 0) Log.d(TAG, "Generating... ${sb.length} chars so far")

                                        val start = text.indexOf('{')
                                        if (start != -1) {
                                            var depth = 0
                                            for (i in start until text.length) {
                                                when (text[i]) {
                                                    '{' -> depth++
                                                    '}' -> if (--depth == 0) {
                                                        earlyResult = text.substring(start, i + 1)
                                                        stopFlag.set(true)
                                                    }
                                                }
                                                if (stopFlag.get()) break
                                            }
                                        }
                                    }
                                    if (done) {
                                        Log.d(TAG, "Generation done. Total: ${sb.length} chars")
                                        cont.resume(earlyResult ?: sb.toString())
                                    }
                                }
                            }
                        }
                    }
                }
            }

            if (response == null) {
                Log.w(TAG, "Vision model timed out"); return null
            }

            Log.d(TAG, "Vision model response: $response")
            val json = extractJson(response)
            ReceiptResponseParser.parse(json ?: response)
        } catch (e: Exception) {
            Log.w(TAG, "Local vision parsing failed: ${e.message}", e)
            null
        }
    }

    private fun extractJson(text: String): String? {
        val start = text.indexOf('{')
        val end = text.lastIndexOf('}')
        return if (start != -1 && end != -1 && end > start) text.substring(start, end + 1) else null
    }

    private fun resizeForVision(src: android.graphics.Bitmap): android.graphics.Bitmap {
        val maxPx = 768
        val w = src.width
        val h = src.height
        if (w <= maxPx && h <= maxPx) return src
        return if (w > h) {
            val newH = (h * maxPx.toFloat() / w).toInt()
            android.graphics.Bitmap.createScaledBitmap(src, maxPx, newH, true)
        } else {
            val newW = (w * maxPx.toFloat() / h).toInt()
            android.graphics.Bitmap.createScaledBitmap(src, newW, maxPx, true)
        }
    }
}
